Ussuri and before: Pin bundler in beaker tests
It seems we forgot adding pin only in beaker tests and installation of
bundler has been failing in Ubuntu Bionic because the version selected
requires newer version of ruby.

ERROR: Error installing bundler:
   ...
   bundler requires Ruby version >= 2.6.0. The current ruby version
   is 2.5.0.
Change-Id: I0a894847154034ac8dec625244a190987fabd12b
(cherry picked from commit 81ba0569755842550ccebd78269dcbd52a4a5d0a)