scenario003: disable sahara on ubuntu jobs
Sahara is broken in Ubuntu / Mitaka:
ConfigParser.NoSectionError: No section: 'alembic'

While Debian is fixing it and Ubuntu is synced, we need to disable
Sahara on Ubuntu so our CI keeps rolling.

Change-Id: Iea74763c25bc52fc7637d201f614f5cbea22f459