Update SSL certificates with SubjectAltNames
A recent update to urllib tightened some checks around SSL [1].
This prompted an update to Devstack in order to work properly [2].

Jobs running into this problem without having a SubjectAltName
provided will see an error that looks like:

    SSLError: hostname '127.0.0.1' doesn't match either of
    '127.0.0.1', 'localhost'

Let's also update the certificates to provide the SubjectAltName
and provide a way to easily update the certificates if required
in the future.

[1]: https://github.com/shazow/urllib3/blob/df9d503a8ea767e8a2ee95b3e75a914480c93de6/CHANGES.rst#118-2016-09-26
[2]: https://git.openstack.org/cgit/openstack-dev/devstack/commit/?id=69e3c0aac99981f17c76c22111e5c397824b8428

Change-Id: I94a586b333ba6a99ef831c853a19ab127b502d6f
(cherry picked from commit 61ba93a2b0b7f812107e700c6fd952cf567d50c6)