Align the stars
CI is currently flacky / broken.

1. ubuntu: exclude test_create_show_delete_firewall from tempest
https://github.com/openstack/tempest/commit/f2088f3b7b28b9d9eae3ee5c4757f2beac0aaf6a
This patch broke us when running Tempest with Ubuntu Ocata.

 File "/usr/lib/python2.7/dist-packages/neutron_fwaas/tests/tempest_plugin/tests/api/test_fwaas_extensions.py", line 102, in _wait_until_ready
  if not test.call_until_true(_wait, CONF.network.build_timeout,
AttributeError: 'module' object has no attribute 'call_until_true'

2. Start Designate services after RabbitMQ resources are ready
This makes sure Designate services can start correctly at first Puppet
run and make second Puppet run idempotent.

3. Disable vitrage which is unstable now, until we figure out what's
wrong with configuration. It seems related to auth parameters.

Change-Id: I84921cbf4f4f838bff4f970113e709181801bed9